# This is a basic workflow to help you get started with Actions
name: Mulitline-Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: step1 -log to pre-build disc space
        run: df
        
      - name: step2 - Checkout the main GitHub branch
        uses: actions/checkout@v2
        
      - name: step3 - Set up JDk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: step4 -Build your jakarta web app with Maven
        run: echo mvn -B package --file pom.xml
      
      
      - name: step5 - Build the native Android App
        run : |
          echo here is tha ANDROID_SDK_ROOT
          echo $ANDROID_SDK_ROOT
      
      - name: step6 - Run your selenium test 
        run: |
          echo the SELENIUM_JAR_PATH
          echo $SELENIUM_JAR_PATH
      
      - name: step7 - log build tool versions
        run: |
          git --version
          mvn --version
          ant -version
          gradle --version
          
      - name: step8 - log the post-build disc space
        run: df
  
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: step1 -log to pre-build disc space
        run: df
        
      - name: step2 - Checkout the main GitHub branch
        uses: actions/checkout@v2
        
      - name: step3 - Set up JDk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: step4 -Build your jakarta web app with Maven
        run: echo mvn -B package --file pom.xml
      
      
      - name: step5 - Build the native Android App
        run : |
          echo here is tha ANDROID_SDK_ROOT
          echo $ANDROID_SDK_ROOT
      
      - name: step6 - Run your selenium test 
        run: |
          echo the SELENIUM_JAR_PATH
          echo $SELENIUM_JAR_PATH
      
      - name: step7 - log build tool versions
        run: |
          git --version
          mvn --version
          ant -version
          gradle --version
          
      - name: step8 - log the post-build disc space
        run: df
